# augment: true
# augment_times: 1
# augment_times_query: 1

# Model
backbone:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
  name: resnet12
batch_size: 128

classifier:
  kwargs:
    feat_dim: 640
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          lr: 0.001
        name: Adam
      inner_train_iter: 100
    num_class: 64
  name: Baseline

# Dataset
data_root: /home/dl_g33/dataset/miniImageNet--ravi
use_memory: True

# Traning setting
deterministic: true
device_ids: 0
episode_size: 1
epoch: 50
train_episode: 100
image_size: 84

includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Baseline.yaml
- backbones/resnet12.yaml

# Log file
log_interval: 100
log_level: info
log_name: null
log_paramerter: false

# Finetune
lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 10
  name: StepLR
n_gpu: 0
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other:
    emb_func: 0.001
parallel_part:
- emb_func
pretrain_path: null
result_root: /home/dl_g33/fsl_git_cath/baselines/LibFewShot/results
resume: false
save_interval: 10
save_part:
- emb_func
seed: 0
shot_num: 1
tag: null
tb_scale: 1.0
test_episode: 100
test_epoch: 5
test_query: 15
test_shot: 1
test_way: 5
num_sampled: 750
test_classifier: LR

base_transform: false