# log settings
log_name: ~ # if not ~: use for log file's name
log_level: info
log_interval: 100
log_paramerter: False # save the parameter as histogram or not

result_root: /home/dl_g33/fsl_git_sherry/baselines/LibFewShot/results/
save_interval: 10
save_part:
  - emb_func

tag: ~
