includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
#  - classifiers/Baseline.yaml
#  - backbones/resnet12.yaml

classifier:
  name: ViTforclassification
#  kwargs:
#    inner_param:
#      inner_optim:
#        name: Adam
#        kwargs:
#          lr: 1e-3
#      inner_train_iter: 100
#      inner_batch_size: 4
#    feat_dim: 640
#    num_class: 64


backbone:
  name: ViT
#  kwargs:
#    keep_prob: 0.0
#    avg_pool: True
#    is_flatten: True

